### PR TITLE
Added license

### PR DESCRIPTION
**Pull request by b1sergiu**
Your code needs a license. I've added the [MIT License](https://choosealicense.com/licenses/mit/) for you to keep it simple and permissive.

### CODE REVIEW

**Comment by Lautenschlager-id** [comment]
Why does it need a license?

**Comment by b1sergiu** [comment]
Any open source code needs a license to clear things up and to avoid conflict between collaborators and users.

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

> Even in the absence of a license file, you may grant some rights in cases where you publish your source code to a site that requires accepting terms of service. For example, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service, by which you allow others to view and fork your repository. Others may not need your permission if limitations and exceptions to copyright apply to their particular situation. Neither site terms nor jurisdiction-specific copyright limitations are sufficient for the kinds of collaboration that people usually seek on a public code host, such as experimentation, modification, and sharing as fostered by an open source license.

I suggested the MIT License to keep it simple for everyone. If you'd like an even more permissive one, you could choose [The Unlicense](https://choosealicense.com/licenses/unlicense/) or even the [Do What The Fuck You Want To Public License](https://choosealicense.com/licenses/wtfpl/).

**Comment by Lautenschlager-id** [comment]
And you're asking for the license because people that currently host their modules as submodes here may face `Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.`?

**Comment by b1sergiu** [comment]
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Basically nobody is legally allowed to do anything without a license.

Is everyone credited in the files?

**Comment by Lautenschlager-id** [comment]
They are, each submode has a `package.lua` file with the author name. But sure, let's add this license.

**Pull request merged**
